# Generated by Django 6.0.4 on 2026-05-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_author_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_time', models.DurationField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='comments_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='followers_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='monetisation_income',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='posts_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='reputation_score',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
